version: "3.8"

services:
  whaticketplusback:
    image: felipergrosa/whaticketplus-backend:latest
    container_name: whaticketplusback
    restart: always
    environment:
      PORT: 8080
      NODE_ENV: production
      DB_DIALECT: postgres
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: whaticketplus
      DB_USER: postgres
      DB_PASS: efe487b6a861100fb704ad9f5c160cb8
      TZ: America/Sao_Paulo
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_URI: redis://redis:6379/0
      JWT_SECRET: umSegredoBemForteAqui123!
      FRONTEND_URL: https://chatplus.nobreluminarias.com.br
    networks:
      - nobreluminarias
    deploy:
      labels:
        traefik.enable: "true"
        traefik.http.routers.whaticketplusback.rule: Host(`chatplusapi.nobreluminarias.com.br`)
        traefik.http.routers.whaticketplusback.entrypoints: websecure
        traefik.http.routers.whaticketplusback.tls.certresolver: letsencryptresolver
        traefik.http.routers.whaticketplusback.service: whaticketplusback
        traefik.http.services.whaticketplusback.loadbalancer.server.port: "8080"
        traefik.http.services.whaticketplusback.loadbalancer.passHostHeader: "true"
        traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto: https
        traefik.http.routers.whaticketplusback.middlewares: sslheader@docker
      resources:
        limits:
          cpus: "0.75"
          memory: 900M
        reservations:
          cpus: "0.25"
          memory: 256M
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
        window: 60s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  whaticketplusfront:
    image: felipergrosa/whaticketplus-frontend:latest
    container_name: whaticketplusfront
    restart: always
    depends_on:
      - whaticketplusback
    networks:
      - nobreluminarias
    environment:
      TZ: America/Sao_Paulo
      SERVER_PORT: 3333
    deploy:
      labels:
        traefik.enable: "true"
        traefik.http.routers.whaticketplusfront.rule: Host(`chatplus.nobreluminarias.com.br`)
        traefik.http.routers.whaticketplusfront.entrypoints: websecure
        traefik.http.routers.whaticketplusfront.tls.certresolver: letsencryptresolver
        traefik.http.routers.whaticketplusfront.service: whaticketplusfront
        traefik.http.services.whaticketplusfront.loadbalancer.server.port: "3333"
        traefik.http.services.whaticketplusfront.loadbalancer.passHostHeader: "true"
        traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto: https
        traefik.http.routers.whaticketplusfront.middlewares: sslheader@docker
      resources:
        limits:
          cpus: "1.5"
          memory: "2G"
        reservations:
          cpus: "1.0"
          memory: "1G"
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
        window: 60s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  whaticketplus_postgres_backup:
    image: prodrigestivill/postgres-backup-local
    container_name: whaticketplus_postgres_backup
    restart: always
    networks:
      - nobreluminarias
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_DB: whaticketplus
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: efe487b6a861100fb704ad9f5c160cb8
      SCHEDULE: "@daily"
      BACKUP_KEEP_DAYS: 7
      S3_ENABLED: "true"
      S3_ACCESS_KEY: NFo5SosZB3vdEuVvHsGl
      S3_SECRET_KEY: oKygVxJ4Jte5RJeUl7alX1UE5S4Fi1iGV9Z69rcs
      S3_BUCKET: whaticketplus
      S3_ENDPOINT: storage.nobreluminarias.com.br
      S3_PORT: 443
      S3_USE_SSL: "true"
      TZ: America/Sao_Paulo
    depends_on:
      - whaticketplusback
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  nobreluminarias:
    external: true
    name: nobreluminarias
